name: 'Pull Request Labeler'
on:
  pull_request_target:
    branches-ignore:
      - 'dependabot/**'

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@4.1.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
